// Generated by https://quicktype.io

export interface City {
  city_Id:       number;
  city_Name:     string;
  state_Code:    number;
  cityShortName: string;
  districtName:  string;
  districtCode:  number;
  cityCode:      number;
}
