// Generated by https://quicktype.io

export interface District {
  district_Code:       number;
  district_Name:       string;
  state_Name:          null;
  district_Short_Name: string;
  city_Code:           number;
  rO_Code:             number;
  state_Code:          number;
}
