// Generated by https://quicktype.io

export interface RegionalOffice {
  rO_Code:       number;
  rO_Name:       string;
  rO_Short_Name: string;
  rO_ERP_Code:   string;
  zO_Code:       number;
  hO_Code:       number;
  district_Code: null;
}
