// Generated by https://quicktype.io

export interface State {
  state_Id:       number;
  state_Name:     string;
  countryRegCode: number;
  zoCode:         number;
  stateShortName: string;
  stateCode:      number;
}
