// Generated by https://quicktype.io

export interface Zone {
  zone_Id:         number;
  zone_Name:       string;
  zone_ERPcode:    string;
  zone_Code:       string;
  zone_Short_Name: string;
  state_Id:        number;
  state_Name:      null;
}
